checks:
    javascript: true
build:
    environment:
        node: '5.1.0'
    dependencies:
        after:
            - npm install jscs
    tests:
        override: 
            -
                command: './node_modules/jscs/bin/jscs . --reporter=json  > jscs-data'
                analysis:
                    file: 'jscs-data'
                    format: 'jscs-json'
